# Generated by Django 5.0.4 on 2024-05-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pno', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='')),
            ],
        ),
    ]
